/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import entidades.FileRenderer;
import entidades.GenericListModel;
import entidades.Personagem;
import entidades.Personagem.Pericia;
import entidades.Personagem.TesteResistencia;
import java.io.File;
import java.util.List;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import persistencia.Arquivo;

/**
 *
 * @author willi
 */
public class JanelaCadastrarPersonagem extends javax.swing.JFrame {
    DefaultListModel<Personagem.Pericia> modeloListaPericias = new DefaultListModel<>();
    DefaultListModel<Personagem.TesteResistencia> modeloListaTestesRes = new DefaultListModel<>();
    
    GenericListModel<Personagem.Pericia> pericias = new GenericListModel<>();
    GenericListModel<Personagem.TesteResistencia> testesRes = new GenericListModel<>();
    
    final String PATH = System.getProperty("user.dir") + "//files//personagens";
    Arquivo<Personagem> arq = new Arquivo<>(PATH);
    DefaultListModel<File> filesModel = new GenericListModel<>(Arquivo.getArquivos(PATH));
    /**
     * Creates new form JanelaCadastrarPersonagem
     */
    public JanelaCadastrarPersonagem() {
        inicializarPericias();
        inicializarTestesRes();
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        personagens_salvosList.setCellRenderer(new FileRenderer());
    }
    
    private void inicializarPericias(){
        Personagem.Pericia[] pericias = Personagem.Pericia.values();
        for(Personagem.Pericia p : pericias){
            modeloListaPericias.addElement(p);
        }
    }
    
    private void inicializarTestesRes(){
        Personagem.TesteResistencia[] testesRes = Personagem.TesteResistencia.values();
        for(Personagem.TesteResistencia tr : testesRes){
            modeloListaTestesRes.addElement(tr);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        janela_consultar_jogadoresFrame = new javax.swing.JFrame();
        personagens_cadastradosLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        personagens_salvosList = new javax.swing.JList();
        consultar_perButtonJanela = new javax.swing.JButton();
        excluirButton = new javax.swing.JButton();
        nomeLabel = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        criadorLabel = new javax.swing.JLabel();
        criadorTextField = new javax.swing.JTextField();
        expLabel = new javax.swing.JLabel();
        expTextField = new javax.swing.JTextField();
        dados_geraisSeparator = new javax.swing.JSeparator();
        nivelLabel = new javax.swing.JLabel();
        nivelTextField = new javax.swing.JTextField();
        classeLabel = new javax.swing.JLabel();
        classeTextField = new javax.swing.JTextField();
        racaLabel = new javax.swing.JLabel();
        racaTextField = new javax.swing.JTextField();
        forLabel = new javax.swing.JLabel();
        desLabel = new javax.swing.JLabel();
        conLabel = new javax.swing.JLabel();
        forTextField = new javax.swing.JTextField();
        desTextField = new javax.swing.JTextField();
        conTextField = new javax.swing.JTextField();
        intLabel = new javax.swing.JLabel();
        sabLabel = new javax.swing.JLabel();
        carLabel = new javax.swing.JLabel();
        intTextField = new javax.swing.JTextField();
        sabTextField = new javax.swing.JTextField();
        carTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        profLabel = new javax.swing.JLabel();
        profTextField = new javax.swing.JTextField();
        caLabel = new javax.swing.JLabel();
        caTextField = new javax.swing.JTextField();
        iniLabel = new javax.swing.JLabel();
        iniTextField = new javax.swing.JTextField();
        vidaLabel = new javax.swing.JLabel();
        vidaTextField = new javax.swing.JTextField();
        vida_tempLabel = new javax.swing.JLabel();
        vida_tempTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        todas_periciasList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        periciasList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        todos_testes_resList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        testes_resList = new javax.swing.JList();
        jSeparator2 = new javax.swing.JSeparator();
        periciasLabel = new javax.swing.JLabel();
        testes_resLabel = new javax.swing.JLabel();
        add_pericButton = new javax.swing.JButton();
        add_teste_resButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        salvarButton = new javax.swing.JButton();
        remover_perButton = new javax.swing.JButton();
        remover_teste_resButton = new javax.swing.JButton();
        npcCheckBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        for_modLabel = new javax.swing.JLabel();
        des_modLabel = new javax.swing.JLabel();
        con_modLabel = new javax.swing.JLabel();
        int_modLabel = new javax.swing.JLabel();
        sab_modLabel = new javax.swing.JLabel();
        car_modLabel = new javax.swing.JLabel();
        total_pontosLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        obsTextArea = new javax.swing.JTextArea();
        obsLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        equipamentoTextArea = new javax.swing.JTextArea();
        equipamentoLabel = new javax.swing.JLabel();
        arcanosPanel = new javax.swing.JPanel();
        consultarButton = new javax.swing.JButton();

        janela_consultar_jogadoresFrame.setAlwaysOnTop(true);
        janela_consultar_jogadoresFrame.setLocation(new java.awt.Point(50, 50));
        janela_consultar_jogadoresFrame.setLocationByPlatform(true);
        janela_consultar_jogadoresFrame.setMinimumSize(new java.awt.Dimension(510, 250));

        personagens_cadastradosLabel.setText("Personagens Cadastrados");

        personagens_salvosList.setModel(filesModel);
        personagens_salvosList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarPersonagemClick(evt);
            }
        });
        jScrollPane7.setViewportView(personagens_salvosList);

        consultar_perButtonJanela.setText("Consultar");
        consultar_perButtonJanela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarPersonagemButton(evt);
            }
        });

        excluirButton.setText("Excluir");
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirPersonagemButton(evt);
            }
        });

        javax.swing.GroupLayout janela_consultar_jogadoresFrameLayout = new javax.swing.GroupLayout(janela_consultar_jogadoresFrame.getContentPane());
        janela_consultar_jogadoresFrame.getContentPane().setLayout(janela_consultar_jogadoresFrameLayout);
        janela_consultar_jogadoresFrameLayout.setHorizontalGroup(
            janela_consultar_jogadoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(janela_consultar_jogadoresFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(janela_consultar_jogadoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(janela_consultar_jogadoresFrameLayout.createSequentialGroup()
                        .addComponent(personagens_cadastradosLabel)
                        .addGap(0, 339, Short.MAX_VALUE))
                    .addComponent(jScrollPane7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, janela_consultar_jogadoresFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(excluirButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultar_perButtonJanela)))
                .addContainerGap())
        );
        janela_consultar_jogadoresFrameLayout.setVerticalGroup(
            janela_consultar_jogadoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(janela_consultar_jogadoresFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personagens_cadastradosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(janela_consultar_jogadoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultar_perButtonJanela)
                    .addComponent(excluirButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nomeLabel.setText("Nome do Personagem*");

        criadorLabel.setText("Criador*");

        criadorTextField.setNextFocusableComponent(classeTextField);

        expLabel.setText("Experiência*");

        expTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        expTextField.setText("0");
        expTextField.setNextFocusableComponent(nivelTextField);

        nivelLabel.setText("Nível*");

        nivelTextField.setColumns(5);
        nivelTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nivelTextField.setText("1");
        nivelTextField.setNextFocusableComponent(npcCheckBox);

        classeLabel.setText("Classe*");

        racaLabel.setText("Raça*");

        racaTextField.setNextFocusableComponent(expTextField);

        forLabel.setText("Força*");

        desLabel.setText("Destreza*");

        conLabel.setText("Constituição*");

        forTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        forTextField.setText("10");
        forTextField.setCaretPosition(0);
        forTextField.setNextFocusableComponent(desTextField);
        forTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                atualizaModFor(evt);
            }
        });

        desTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        desTextField.setText("10");
        desTextField.setNextFocusableComponent(conTextField);
        desTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                atualizaModDes(evt);
            }
        });

        conTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        conTextField.setText("10");
        conTextField.setNextFocusableComponent(intTextField);
        conTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                atualizaModCon(evt);
            }
        });

        intLabel.setText("Inteligência*");

        sabLabel.setText("Sabedoria*");

        carLabel.setText("Carisma*");

        intTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        intTextField.setText("10");
        intTextField.setNextFocusableComponent(sabTextField);
        intTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                atualizaModInt(evt);
            }
        });

        sabTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sabTextField.setText("10");
        sabTextField.setNextFocusableComponent(carTextField);
        sabTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                atualizaModSab(evt);
            }
        });

        carTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        carTextField.setText("10");
        carTextField.setNextFocusableComponent(profTextField);
        carTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                atualizaModCar(evt);
            }
        });

        profLabel.setText("Proficiência*");

        profTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        profTextField.setText("2");
        profTextField.setNextFocusableComponent(caTextField);

        caLabel.setText("Classe de Armadura*");

        caTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        caTextField.setText("10");
        caTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        caTextField.setNextFocusableComponent(iniTextField);

        iniLabel.setText("Iniciativa*");

        iniTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iniTextField.setText("0");
        iniTextField.setNextFocusableComponent(vidaTextField);

        vidaLabel.setText("Pontos de Vida*");

        vidaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vidaTextField.setText("0");
        vidaTextField.setNextFocusableComponent(vida_tempTextField);

        vida_tempLabel.setText("Pontos de Vida Temporários*");

        vida_tempTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vida_tempTextField.setText("0");
        vida_tempTextField.setNextFocusableComponent(todas_periciasList);

        todas_periciasList.setModel(modeloListaPericias);
        todas_periciasList.setNextFocusableComponent(todos_testes_resList);
        todas_periciasList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adcionarPericiaClick(evt);
            }
        });
        jScrollPane1.setViewportView(todas_periciasList);

        jLabel1.setText("<->");

        periciasList.setModel(pericias);
        periciasList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(periciasList);

        todos_testes_resList.setModel(modeloListaTestesRes);
        todos_testes_resList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        todos_testes_resList.setNextFocusableComponent(salvarButton);
        todos_testes_resList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adicionarTesteResClick(evt);
            }
        });
        jScrollPane3.setViewportView(todos_testes_resList);

        jLabel2.setText("<->");

        testes_resList.setModel(testesRes);
        jScrollPane4.setViewportView(testes_resList);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        periciasLabel.setText("Perícias Proficientes*");

        testes_resLabel.setText("Testes de Resistência Proficientes*");

        add_pericButton.setText("Adicionar");
        add_pericButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adcionarPericia(evt);
            }
        });

        add_teste_resButton.setText("Adicionar");
        add_teste_resButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarTesteRes(evt);
            }
        });

        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarPersonagem(evt);
            }
        });

        remover_perButton.setText("Remover");
        remover_perButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerPericia(evt);
            }
        });

        remover_teste_resButton.setText("Remover");
        remover_teste_resButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerTesteRes(evt);
            }
        });

        npcCheckBox.setText("NPC");
        npcCheckBox.setNextFocusableComponent(forTextField);
        npcCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isNPC(evt);
            }
        });

        jLabel5.setText("* campos obrigatórios");

        for_modLabel.setText("+0");

        des_modLabel.setText("+0");

        con_modLabel.setText("+0");

        int_modLabel.setText("+0");

        sab_modLabel.setText("+0");

        car_modLabel.setText("+0");

        total_pontosLabel.setText("Total de Pontos:");

        totalLabel.setText("60");

        obsTextArea.setColumns(20);
        obsTextArea.setRows(5);
        jScrollPane6.setViewportView(obsTextArea);

        obsLabel.setText("Observação");

        equipamentoTextArea.setColumns(20);
        equipamentoTextArea.setRows(5);
        jScrollPane5.setViewportView(equipamentoTextArea);

        equipamentoLabel.setText("Equipamento");

        javax.swing.GroupLayout arcanosPanelLayout = new javax.swing.GroupLayout(arcanosPanel);
        arcanosPanel.setLayout(arcanosPanelLayout);
        arcanosPanelLayout.setHorizontalGroup(
            arcanosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        arcanosPanelLayout.setVerticalGroup(
            arcanosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarPersonagemJanela(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consultarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salvarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(add_pericButton)
                                                .addGap(42, 42, 42)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(remover_perButton)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addComponent(periciasLabel)))
                                .addGap(12, 12, 12)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(add_teste_resButton)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(remover_teste_resButton)))
                                    .addComponent(testes_resLabel)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nomeLabel)
                                        .addComponent(classeLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(classeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(nomeTextField))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(criadorLabel))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(racaLabel)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(racaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                        .addComponent(criadorTextField))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(59, 59, 59)
                                            .addComponent(expLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(expTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nivelLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nivelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(npcCheckBox))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(conLabel)
                                            .addComponent(forLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(desLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(total_pontosLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(totalLabel)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(forTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(desTextField)
                                                .addComponent(conTextField))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(con_modLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(carLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(carTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(for_modLabel)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(intLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(intTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(des_modLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(sabLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(sabTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(car_modLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(iniLabel))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(int_modLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(profLabel))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(sab_modLabel)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(caLabel)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(profTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(iniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(vida_tempLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(vida_tempTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(caTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(vidaLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(vidaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addComponent(dados_geraisSeparator, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(obsLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(equipamentoLabel)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(arcanosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeLabel)
                            .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criadorLabel)
                            .addComponent(criadorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expLabel)
                            .addComponent(expTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nivelLabel)
                            .addComponent(nivelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classeLabel)
                            .addComponent(classeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(racaLabel)
                            .addComponent(racaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(npcCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dados_geraisSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(profLabel)
                                .addComponent(profTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(forLabel)
                                .addComponent(forTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(for_modLabel)
                                .addComponent(intLabel)
                                .addComponent(intTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(int_modLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(desLabel)
                            .addComponent(desTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(des_modLabel)
                            .addComponent(sabLabel)
                            .addComponent(sabTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sab_modLabel)
                            .addComponent(caLabel)
                            .addComponent(caTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vidaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vidaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(conLabel)
                            .addComponent(conTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(con_modLabel)
                            .addComponent(carLabel)
                            .addComponent(carTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(car_modLabel)
                            .addComponent(iniLabel)
                            .addComponent(iniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vida_tempTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vida_tempLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalLabel)
                            .addComponent(total_pontosLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(periciasLabel)
                                    .addComponent(testes_resLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(jLabel1))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(remover_perButton)
                                            .addComponent(add_pericButton)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(jLabel2))
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(jScrollPane4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(add_teste_resButton)
                                            .addComponent(remover_teste_resButton)))))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(obsLabel)
                            .addComponent(equipamentoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane6))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(arcanosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarButton)
                    .addComponent(jLabel5)
                    .addComponent(consultarButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adcionarPericia(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adcionarPericia
        Pericia per = (Pericia) todas_periciasList.getSelectedValue();
        pericias.add(per);
    }//GEN-LAST:event_adcionarPericia

    private void adicionarTesteRes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarTesteRes
        TesteResistencia tr = (TesteResistencia) todos_testes_resList.getSelectedValue();
        testesRes.add(tr);
    }//GEN-LAST:event_adicionarTesteRes

    private void salvarPersonagem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarPersonagem
        
        try {
            String mensagem_erro = null;
            Personagem personagem = obtemPersonagemInformado();
            Arquivo<Personagem> arq = null;
            
            if(personagem == null){
                mensagem_erro = "Algum dado do personagem não foi informado!";
                JOptionPane.showMessageDialog(this, mensagem_erro, "Informação", JOptionPane.INFORMATION_MESSAGE);
            }else{
                if(Personagem.existePer(personagem.getNome())) {
                    mensagem_erro = "Personagem " + personagem.getNome() + " já existe, deseja substituílo?";
                    int substituir = JOptionPane.showConfirmDialog(this, mensagem_erro, "ATENÇÂO", JOptionPane.WARNING_MESSAGE);
                    if(substituir == 0){
                        arq = new Arquivo<>(System.getProperty("user.dir") + "//files//personagens//" + personagem.getNome() + ".per");
                        mensagem_erro = arq.salvar(personagem);
                        JOptionPane.showMessageDialog(this, mensagem_erro, "Informação", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                else {
                    arq = new Arquivo<>(System.getProperty("user.dir") + "//files//personagens//" + personagem.getNome() + ".per");
                    mensagem_erro = arq.salvar(personagem);
                    JOptionPane.showMessageDialog(this, mensagem_erro, "Informação", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
            
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_salvarPersonagem
    
    private Personagem obtemPersonagemInformado(){
        String nome = nomeTextField.getText();
        if(nome.isEmpty()) return null;
        String criador = criadorTextField.getText();
        if(!npcCheckBox.isSelected() && criador.isEmpty()) return null;
        String classe = classeTextField.getText();
        if(classe.isEmpty()) return null;
        String raca = racaTextField.getText();
        if(raca.isEmpty()) return null;
        
        int exp = Integer.parseInt(expTextField.getText());
        int nivel = Integer.parseInt(nivelTextField.getText());
        
        int[] atributos = new int[6];
        atributos[0] = Integer.parseInt(forTextField.getText());
        atributos[1] = Integer.parseInt(desTextField.getText());
        atributos[2] = Integer.parseInt(conTextField.getText());
        atributos[3] = Integer.parseInt(intTextField.getText());
        atributos[4] = Integer.parseInt(sabTextField.getText());
        atributos[5] = Integer.parseInt(carTextField.getText());
        
        int proficiencia = Integer.parseInt(profTextField.getText());
        int classeArmadura = Integer.parseInt(caTextField.getText());
        int iniciativa = Integer.parseInt(iniTextField.getText());
        
        int vida = Integer.parseInt(vidaTextField.getText());
        int vida_temp = Integer.parseInt(vida_tempTextField.getText());
        
        
        Pericia[] pers = new Pericia[pericias.getSize()];
        if(!npcCheckBox.isSelected() && pers.length == 0 ) return null;
        System.arraycopy(pericias.toArray(), 0, pers, 0, pericias.getSize());
        TesteResistencia[] teste_resistencia = new TesteResistencia[testesRes.getSize()];
        if(!npcCheckBox.isSelected() && teste_resistencia.length == 0 ) return null;
        System.arraycopy(testesRes.toArray(), 0, teste_resistencia, 0, testesRes.getSize());
        
        String equipamento = equipamentoTextArea.getText();
        String obs = obsTextArea.getText();
        
        if(npcCheckBox.isSelected()) return new Personagem(nome, classe, raca, iniciativa, vida, atributos);
        
        return new Personagem(nome, criador, classe, raca, equipamento, obs, proficiencia, classeArmadura, iniciativa, vida, vida_temp, exp, nivel, atributos, pers, teste_resistencia);
    }
    
    private void removerPericia(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerPericia
        Pericia per = (Pericia) periciasList.getSelectedValue();
        pericias.removeElement(per);
    }//GEN-LAST:event_removerPericia

    private void removerTesteRes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerTesteRes
        TesteResistencia tr = (TesteResistencia) testes_resList.getSelectedValue();
        testesRes.removeElement(tr);
    }//GEN-LAST:event_removerTesteRes

    private void adcionarPericiaClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adcionarPericiaClick
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            Pericia per = (Pericia) todas_periciasList.getSelectedValue();
            pericias.add(per);
        }
        
    }//GEN-LAST:event_adcionarPericiaClick

    private void adicionarTesteResClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionarTesteResClick
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            TesteResistencia tr = (TesteResistencia) todos_testes_resList.getSelectedValue();
            testesRes.add(tr);
        }
    }//GEN-LAST:event_adicionarTesteResClick

    private void isNPC(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isNPC
        /*nome, classe, raca, iniciativa, vida, atributos*/
        /*criador, proficiencia, classeArmadura, vida_temp, exp, nivel, pers, teste_resistencia*/
        if(npcCheckBox.isSelected()){
            criadorLabel.setText("Criador");
            profLabel.setText("Proficiência");
            caLabel.setText("Classe de Armadura");
            vida_tempLabel.setText("Pontos de Vida");
            expLabel.setText("Experiência");
            nivelLabel.setText("Nível");
            periciasLabel.setText("Perícias Proficientes");
            testes_resLabel.setText("Testes de Resistência Proficientes");
        }else{
            criadorLabel.setText("Criador*");
            profLabel.setText("Proficiência*");
            caLabel.setText("Classe de Armadura*");
            vida_tempLabel.setText("Pontos de Vida*");
            expLabel.setText("Experiência*");
            nivelLabel.setText("Nível*");
            periciasLabel.setText("Perícias Proficientes*");
            testes_resLabel.setText("Testes de Resistência Proficientes*");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_isNPC
    private void atualizaTotalPontos(){
        int n = Integer.parseInt(forTextField.getText()) + 
                Integer.parseInt(desTextField.getText()) + 
                Integer.parseInt(conTextField.getText()) + 
                Integer.parseInt(intTextField.getText()) +
                Integer.parseInt(sabTextField.getText()) +
                Integer.parseInt(carTextField.getText());
        totalLabel.setText("" + n);
    }
    private void atualizaModFor(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_atualizaModFor
        int num = (Integer.parseInt(forTextField.getText())/2) - 5;
        for_modLabel.setText("" + (num>=0 ? "+" : "") + num);
        atualizaTotalPontos();
    }//GEN-LAST:event_atualizaModFor

    private void atualizaModDes(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_atualizaModDes
        int num = (Integer.parseInt(desTextField.getText())/2) - 5;
        des_modLabel.setText("" + (num>=0 ? "+" : "") + num);
        atualizaTotalPontos();
    }//GEN-LAST:event_atualizaModDes

    private void atualizaModCon(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_atualizaModCon
        int num = (Integer.parseInt(conTextField.getText())/2) - 5;
        con_modLabel.setText("" + (num>=0 ? "+" : "") + num);
        atualizaTotalPontos();
    }//GEN-LAST:event_atualizaModCon

    private void atualizaModInt(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_atualizaModInt
        int num = (Integer.parseInt(intTextField.getText())/2) - 5;
        int_modLabel.setText("" + (num>=0 ? "+" : "") + num);
        atualizaTotalPontos();
    }//GEN-LAST:event_atualizaModInt

    private void atualizaModSab(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_atualizaModSab
        int num = (Integer.parseInt(sabTextField.getText())/2) - 5;
        sab_modLabel.setText("" + (num>=0 ? "+" : "") + num);
        atualizaTotalPontos();
    }//GEN-LAST:event_atualizaModSab

    private void atualizaModCar(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_atualizaModCar
        int num = (Integer.parseInt(carTextField.getText())/2) - 5;
        car_modLabel.setText("" + (num>=0 ? "+" : "") + num);
        atualizaTotalPontos();
    }//GEN-LAST:event_atualizaModCar

    private void consultarPersonagemJanela(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarPersonagemJanela
        filesModel = new GenericListModel<>(Arquivo.getArquivos(PATH));
        personagens_salvosList.setModel(filesModel);
        janela_consultar_jogadoresFrame.setVisible(true);
    }//GEN-LAST:event_consultarPersonagemJanela

    private void consultarPersonagemButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarPersonagemButton
        File file = (File)personagens_salvosList.getSelectedValue();
        Personagem per;
        try {
            per = arq.carregar(file.getAbsolutePath());
            nomeTextField.setText(per.getNome());
            classeTextField.setText(per.getClasse());
            criadorTextField.setText(per.getCriador());
            racaTextField.setText(per.getRaca());
            expTextField.setText(""+per.getExp());
            nivelTextField.setText(""+per.getNivel());

            forTextField.setText("" + per.getAtributos()[0]);
            desTextField.setText("" + per.getAtributos()[1]);
            conTextField.setText("" + per.getAtributos()[2]);
            intTextField.setText("" + per.getAtributos()[3]);
            sabTextField.setText("" + per.getAtributos()[4]);
            carTextField.setText("" + per.getAtributos()[5]);

            profTextField.setText("" + per.getProficiencia());
            caTextField.setText("" + per.getClasseArmadura());
            iniTextField.setText("" + per.getIniciativa());

            vidaTextField.setText("" + per.getVida());
            vida_tempTextField.setText("" + per.getVidaTemp());

            for(Pericia p : per.getPericias()){
                pericias.add(p);
            }

            for(TesteResistencia tr : per.getTestes_res()){
                testesRes.add(tr);
            }

            obsTextArea.setText(per.getObs());
            equipamentoTextArea.setText(per.getEquipamento());
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JanelaEscudo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_consultarPersonagemButton

    private void excluirPersonagemButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirPersonagemButton
        File file = (File)personagens_salvosList.getSelectedValue();
        try {
            int excluir = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja apagar o personagem PERMANENTEMENTE?", "ATENÇÂO", JOptionPane.WARNING_MESSAGE);
            if(excluir == 0){
                if(file.delete()){
                    filesModel.removeElement(file);
                    JOptionPane.showMessageDialog(this, file.getName() + " foi apagado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, "Falha na operação! Arquivo não excluído.", "Informação", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_excluirPersonagemButton

    private void consultarPersonagemClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarPersonagemClick
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            File file = (File)personagens_salvosList.getSelectedValue();
            Personagem per;
            try {
                per = arq.carregar(file.getAbsolutePath());
                nomeTextField.setText(per.getNome());
                classeTextField.setText(per.getClasse());
                criadorTextField.setText(per.getCriador());
                racaTextField.setText(per.getRaca());
                expTextField.setText(""+per.getExp());
                nivelTextField.setText(""+per.getNivel());

                forTextField.setText("" + per.getAtributos()[0]);
                desTextField.setText("" + per.getAtributos()[1]);
                conTextField.setText("" + per.getAtributos()[2]);
                intTextField.setText("" + per.getAtributos()[3]);
                sabTextField.setText("" + per.getAtributos()[4]);
                carTextField.setText("" + per.getAtributos()[5]);

                profTextField.setText("" + per.getProficiencia());
                caTextField.setText("" + per.getClasseArmadura());
                iniTextField.setText("" + per.getIniciativa());

                vidaTextField.setText("" + per.getVida());
                vida_tempTextField.setText("" + per.getVidaTemp());

                pericias.clear();
                for(Pericia p : per.getPericias()){
                    pericias.add(p);
                }

                testesRes.clear();
                for(TesteResistencia tr : per.getTestes_res()){
                    testesRes.add(tr);
                }

                obsTextArea.setText(per.getObs());
                equipamentoTextArea.setText(per.getEquipamento());

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(JanelaEscudo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_consultarPersonagemClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadastrarPersonagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_pericButton;
    private javax.swing.JButton add_teste_resButton;
    private javax.swing.JPanel arcanosPanel;
    private javax.swing.JLabel caLabel;
    private javax.swing.JTextField caTextField;
    private javax.swing.JLabel carLabel;
    private javax.swing.JTextField carTextField;
    private javax.swing.JLabel car_modLabel;
    private javax.swing.JLabel classeLabel;
    private javax.swing.JTextField classeTextField;
    private javax.swing.JLabel conLabel;
    private javax.swing.JTextField conTextField;
    private javax.swing.JLabel con_modLabel;
    private javax.swing.JButton consultarButton;
    private javax.swing.JButton consultar_perButtonJanela;
    private javax.swing.JLabel criadorLabel;
    private javax.swing.JTextField criadorTextField;
    private javax.swing.JSeparator dados_geraisSeparator;
    private javax.swing.JLabel desLabel;
    private javax.swing.JTextField desTextField;
    private javax.swing.JLabel des_modLabel;
    private javax.swing.JLabel equipamentoLabel;
    private javax.swing.JTextArea equipamentoTextArea;
    private javax.swing.JButton excluirButton;
    private javax.swing.JLabel expLabel;
    private javax.swing.JTextField expTextField;
    private javax.swing.JLabel forLabel;
    private javax.swing.JTextField forTextField;
    private javax.swing.JLabel for_modLabel;
    private javax.swing.JLabel iniLabel;
    private javax.swing.JTextField iniTextField;
    private javax.swing.JLabel intLabel;
    private javax.swing.JTextField intTextField;
    private javax.swing.JLabel int_modLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JFrame janela_consultar_jogadoresFrame;
    private javax.swing.JLabel nivelLabel;
    private javax.swing.JTextField nivelTextField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JCheckBox npcCheckBox;
    private javax.swing.JLabel obsLabel;
    private javax.swing.JTextArea obsTextArea;
    private javax.swing.JLabel periciasLabel;
    private javax.swing.JList periciasList;
    private javax.swing.JLabel personagens_cadastradosLabel;
    private javax.swing.JList personagens_salvosList;
    private javax.swing.JLabel profLabel;
    private javax.swing.JTextField profTextField;
    private javax.swing.JLabel racaLabel;
    private javax.swing.JTextField racaTextField;
    private javax.swing.JButton remover_perButton;
    private javax.swing.JButton remover_teste_resButton;
    private javax.swing.JLabel sabLabel;
    private javax.swing.JTextField sabTextField;
    private javax.swing.JLabel sab_modLabel;
    private javax.swing.JButton salvarButton;
    private javax.swing.JLabel testes_resLabel;
    private javax.swing.JList testes_resList;
    private javax.swing.JList todas_periciasList;
    private javax.swing.JList todos_testes_resList;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel total_pontosLabel;
    private javax.swing.JLabel vidaLabel;
    private javax.swing.JTextField vidaTextField;
    private javax.swing.JLabel vida_tempLabel;
    private javax.swing.JTextField vida_tempTextField;
    // End of variables declaration//GEN-END:variables
}
