/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.io.File;

/**
 *
 * @author alik
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        new File(System.getProperty("user.dir") + "/files/personagens").mkdirs();
        new File(System.getProperty("user.dir") + "/files/escudos").mkdirs();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_principalMenuBar = new javax.swing.JMenuBar();
        personagemMenu = new javax.swing.JMenu();
        criar_personagemMenuItem = new javax.swing.JMenuItem();
        listar_personagensMenuItem = new javax.swing.JMenuItem();
        mestreMenu = new javax.swing.JMenu();
        escudoMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personagemMenu.setText("Personagem");

        criar_personagemMenuItem.setText("Criar");
        criar_personagemMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarPersonagem(evt);
            }
        });
        personagemMenu.add(criar_personagemMenuItem);

        listar_personagensMenuItem.setText("Listar");
        personagemMenu.add(listar_personagensMenuItem);

        menu_principalMenuBar.add(personagemMenu);

        mestreMenu.setText("Mestre");

        escudoMenuItem.setText("Escudo");
        escudoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escudoMenuItemActionPerformed(evt);
            }
        });
        mestreMenu.add(escudoMenuItem);

        menu_principalMenuBar.add(mestreMenu);

        setJMenuBar(menu_principalMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criarPersonagem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarPersonagem
        new JanelaCadastrarPersonagem().setVisible(true);
    }//GEN-LAST:event_criarPersonagem

    private void escudoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escudoMenuItemActionPerformed
        new JanelaEscudo().setVisible(true);
    }//GEN-LAST:event_escudoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem criar_personagemMenuItem;
    private javax.swing.JMenuItem escudoMenuItem;
    private javax.swing.JMenuItem listar_personagensMenuItem;
    private javax.swing.JMenuBar menu_principalMenuBar;
    private javax.swing.JMenu mestreMenu;
    private javax.swing.JMenu personagemMenu;
    // End of variables declaration//GEN-END:variables
}
